### ISSUE TITLE
web of science

### ISSUE THREAD

**Issue by jessicatytam** [jessicatytam/specieshindex#35]
https://github.com/juba/rwos

**Comment by jessicatytam** [comment]
try other open source databases first

**Comment by jessicatytam** [comment]
i am working on this now since Pietro requested it a few times
doesn't seem to be too hard, just need to figure out the query string

**Comment by jessicatytam** [comment]
check why fetch is downloading much more records than count
figure out TAK query string

**Comment by jessicatytam** [comment]
need to also test query with synonyms and additional keywords

**Comment by mlagisz** [comment]
@jessicatytam in WOS the closest equivalent is TS= (); but note this is not exactly the same as o TITLE-ABS-KEY in Scopus because TS includes "KeyWords Plus", which are assigned by the database moderators, not authors  https://support.clarivate.com/ScientificandAcademicResearch/s/article/KeyWords-Plus-generation-creation-and-changes?language=en_US

**Comment by jessicatytam** [comment]
I guess we can try "TI = () AND AB = () AND AK ()"
it will be longer but i think it's better if we match it with scopus

**Comment by mlagisz** [comment]
yes, this would be the best solution but you need to use OR, not AND to join the fields

**Comment by jessicatytam** [comment]
looks like it's working now!

**Comment by jessicatytam** [comment]
the web of science fetch functions do not work if i load them from the library, but works when I load them individually onto my environment from the Rmd file 🥴
